/**
 * Markdown report builders.
 *
 * Each command writes its result to a Markdown file in the project root
 * (review.md, security-*.md, architecture.md, pr-summary.md, …) rather than the
 * terminal, so these functions turn backend results into those documents.
 */

import type { ReviewFinding } from "../types/review.js";
import type { SecurityFinding, SecurityStats } from "../types/security.js";
import type { ConsensusFinding } from "./consensus.js";

/**
 * Build a Markdown report for a review (for saving to review.md).
 */
export function buildReviewMarkdown(
  findings: ReviewFinding[],
  summary: string,
  providerUsed: string,
  modelUsed: string,
  generatedAt: string
): string {
  const severityOrder = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
  const sorted = [...findings].sort((a, b) => {
    const aVal = severityOrder[a.severity.toUpperCase() as keyof typeof severityOrder] ?? 4;
    const bVal = severityOrder[b.severity.toUpperCase() as keyof typeof severityOrder] ?? 4;
    return aVal - bVal;
  });

  const model = modelUsed ? `${providerUsed}/${modelUsed}` : providerUsed;
  const lines: string[] = [
    "# Code Review",
    "",
    `> Generated by CodeJaguar · ${model} · ${findings.length} issue${findings.length !== 1 ? "s" : ""} found · ${generatedAt}`,
    "",
  ];

  if (summary) {
    lines.push("## Summary", "", summary, "");
  }

  if (sorted.length === 0) {
    lines.push("✅ No issues found. Code looks good!", "");
    return lines.join("\n");
  }

  lines.push("## Findings", "");
  for (const finding of sorted) {
    const location = finding.line ? `${finding.file}:${finding.line}` : finding.file;
    lines.push(
      `### [${finding.severity.toUpperCase()}] ${finding.category} — \`${location}\``,
      "",
      `**Description:** ${finding.description}`,
      "",
      `**Impact:** ${finding.impact}`,
      "",
      `**Recommendation:** ${finding.recommendation}`,
      ""
    );
  }

  return lines.join("\n");
}

/**
 * Build a Markdown report for a security scan (for saving to disk).
 */
export function buildSecurityMarkdown(
  findings: SecurityFinding[],
  stats: SecurityStats,
  providerUsed: string,
  modelUsed: string,
  scanLabel: string,
  generatedAt: string
): string {
  const severityOrder = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
  const sorted = [...findings].sort((a, b) => {
    const aVal = severityOrder[a.severity.toUpperCase() as keyof typeof severityOrder] ?? 4;
    const bVal = severityOrder[b.severity.toUpperCase() as keyof typeof severityOrder] ?? 4;
    return aVal - bVal;
  });

  const model = modelUsed ? `${providerUsed}/${modelUsed}` : providerUsed;
  const lines: string[] = [
    `# Security Scan — ${scanLabel}`,
    "",
    `> Generated by CodeJaguar · ${model} · ${generatedAt}`,
    "",
    `**Summary:** ${stats.critical} critical · ${stats.high} high · ${stats.medium} medium · ${stats.low} low`,
    "",
  ];

  if (sorted.length === 0) {
    lines.push("✅ No security issues found.", "");
    return lines.join("\n");
  }

  lines.push("## Findings", "");
  for (const finding of sorted) {
    const location = finding.line ? `${finding.file}:${finding.line}` : finding.file;
    lines.push(`### [${finding.severity.toUpperCase()}] ${finding.category} — \`${location}\``, "");
    if (finding.module) {
      lines.push(`**Module:** ${finding.module}`, "");
    }
    lines.push(
      `**Description:** ${finding.description}`,
      "",
      `**Impact:** ${finding.impact}`,
      "",
      `**Recommendation:** ${finding.recommendation}`,
      ""
    );
  }

  return lines.join("\n");
}

/** A single architecture finding (mirrors the backend ArchitectureFinding). */
export interface ArchitectureFinding {
  severity: string;
  category: string;
  file?: string;
  description: string;
  recommendation: string;
}

/**
 * Build a Markdown report for an architecture review (for saving to disk).
 */
export function buildArchitectureMarkdown(
  findings: ArchitectureFinding[],
  improvements: string[],
  recommendations: string,
  providerUsed: string,
  modelUsed: string,
  generatedAt: string
): string {
  const severityOrder = { HIGH: 0, MEDIUM: 1, LOW: 2 };
  const sorted = [...findings].sort((a, b) => {
    const aVal = severityOrder[a.severity.toUpperCase() as keyof typeof severityOrder] ?? 3;
    const bVal = severityOrder[b.severity.toUpperCase() as keyof typeof severityOrder] ?? 3;
    return aVal - bVal;
  });

  const model = modelUsed ? `${providerUsed}/${modelUsed}` : providerUsed;
  const lines: string[] = [
    "# Architecture Review",
    "",
    `> Generated by CodeJaguar · ${model} · ${findings.length} finding${findings.length !== 1 ? "s" : ""} · ${generatedAt}`,
    "",
  ];

  if (sorted.length > 0) {
    lines.push("## Findings", "");
    for (const finding of sorted) {
      const where = finding.file ? ` — \`${finding.file}\`` : "";
      lines.push(
        `### [${finding.severity.toUpperCase()}] ${finding.category}${where}`,
        "",
        `**Description:** ${finding.description}`,
        "",
        `**Recommendation:** ${finding.recommendation}`,
        ""
      );
    }
  } else {
    lines.push("✅ No architectural issues found.", "");
  }

  if (improvements.length > 0) {
    lines.push("## Improvements", "");
    for (const imp of improvements) {
      lines.push(`- ${imp}`);
    }
    lines.push("");
  }

  if (recommendations) {
    lines.push("## Recommendations", "", recommendations, "");
  }

  return lines.join("\n");
}

/**
 * Build a Markdown document for a PR summary (for saving to disk).
 *
 * The backend already returns GitHub-ready Markdown; this just prepends a
 * provenance header comment.
 */
export function buildSummaryMarkdown(
  markdown: string,
  providerUsed: string,
  modelUsed: string,
  generatedAt: string
): string {
  const model = modelUsed ? `${providerUsed}/${modelUsed}` : providerUsed;
  return (
    `<!-- Generated by CodeJaguar · ${model} · ${generatedAt} -->\n\n` +
    markdown.trim() +
    "\n"
  );
}

/**
 * Build a Markdown report for a consensus review (for saving to disk).
 *
 * Shows only findings agreed on by multiple providers, annotated with which
 * models agreed on each.
 */
export function buildConsensusMarkdown(
  findings: ConsensusFinding[],
  providers: string[],
  minAgree: number,
  generatedAt: string
): string {
  const lines: string[] = [
    "# Code Review — Consensus",
    "",
    `> Generated by CodeJaguar · ${providers.join(", ")} · ` +
      `${findings.length} agreed finding${findings.length !== 1 ? "s" : ""} ` +
      `(≥${minAgree} of ${providers.length} models) · ${generatedAt}`,
    "",
  ];

  if (findings.length === 0) {
    lines.push(
      `✅ No findings were agreed on by at least ${minAgree} of the ${providers.length} providers.`,
      ""
    );
    return lines.join("\n");
  }

  lines.push("## Agreed Findings", "");
  for (const finding of findings) {
    const location = finding.line ? `${finding.file}:${finding.line}` : finding.file;
    lines.push(
      `### [${finding.severity.toUpperCase()}] ${finding.category} — \`${location}\``,
      "",
      `**Agreed by:** ${finding.agreedBy.join(", ")} (${finding.agreedBy.length}/${providers.length})`,
      "",
      `**Description:** ${finding.description}`,
      "",
      `**Impact:** ${finding.impact}`,
      "",
      `**Recommendation:** ${finding.recommendation}`,
      ""
    );
  }

  return lines.join("\n");
}