/**
 * Terminal output rendering service.
 *
 * Formats and displays results with colored output,
 * structured finding cards, and styled boxes.
 */

import chalk from "chalk";
import boxen from "boxen";
import table from "text-table";
import type { ReviewFinding } from "../types/review.js";
import type { SecurityFinding, SecurityStats } from "../types/security.js";
import type { ConsensusFinding } from "./consensus.js";

/**
 * Get the chalk color for a severity level.
 */
function severityColor(severity: string) {
  switch (severity.toUpperCase()) {
    case "CRITICAL":
      return chalk.hex("#FF0000").bold;
    case "HIGH":
      return chalk.hex("#FF8C00").bold;
    case "MEDIUM":
      return chalk.hex("#FFD700").bold;
    case "LOW":
      return chalk.hex("#4169E1").bold;
    default:
      return chalk.white;
  }
}

/**
 * Render the header box for a result set.
 */
function renderHeader(title: string, subtitle: string): string {
  return boxen(
    chalk.bold.white(title) + "\n" + chalk.gray(subtitle),
    {
      padding: 1,
      margin: 1,
      borderStyle: "round",
      borderColor: "cyan",
    }
  );
}

/**
 * Render a single review finding card.
 */
function renderReviewFinding(finding: ReviewFinding, index: number): string {
  const color = severityColor(finding.severity);
  const location = finding.line
    ? `${finding.file}:${finding.line}`
    : finding.file;

  const lines = [
    color(`[${finding.severity}]`) +
      " " +
      chalk.bold(finding.category) +
      " — " +
      chalk.cyan(location),
    "",
    "  " + chalk.white(finding.description),
    "  " + chalk.gray("Impact: ") + finding.impact,
    "  " + chalk.gray("Fix: ") + chalk.green(finding.recommendation),
  ];

  return lines.join("\n");
}

/**
 * Render review results to the terminal.
 */
export function renderReviewResults(
  findings: ReviewFinding[],
  summary: string,
  providerUsed: string,
  modelUsed: string
): void {
  const header = renderHeader(
    "🔍 Code Review Results",
    `${findings.length} issue${findings.length !== 1 ? "s" : ""} found · ${providerUsed}/${modelUsed}`
  );

  console.log(header);

  if (findings.length === 0) {
    console.log(chalk.green("✅ No issues found. Code looks good!"));
    if (summary) {
      console.log("\n" + chalk.gray("Summary: ") + summary);
    }
    return;
  }

  // Sort by severity (CRITICAL > HIGH > MEDIUM > LOW)
  const severityOrder = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
  const sorted = [...findings].sort((a, b) => {
    const aVal = severityOrder[a.severity.toUpperCase() as keyof typeof severityOrder] ?? 4;
    const bVal = severityOrder[b.severity.toUpperCase() as keyof typeof severityOrder] ?? 4;
    return aVal - bVal;
  });

  for (const [i, finding] of sorted.entries()) {
    console.log(renderReviewFinding(finding, i));
    console.log("");
  }

  if (summary) {
    console.log(chalk.bold("Summary: ") + summary);
  }
}

/**
 * Build a Markdown report for a review (for saving to review.md).
 */
export function buildReviewMarkdown(
  findings: ReviewFinding[],
  summary: string,
  providerUsed: string,
  modelUsed: string,
  generatedAt: string
): string {
  const severityOrder = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
  const sorted = [...findings].sort((a, b) => {
    const aVal = severityOrder[a.severity.toUpperCase() as keyof typeof severityOrder] ?? 4;
    const bVal = severityOrder[b.severity.toUpperCase() as keyof typeof severityOrder] ?? 4;
    return aVal - bVal;
  });

  const model = modelUsed ? `${providerUsed}/${modelUsed}` : providerUsed;
  const lines: string[] = [
    "# Code Review",
    "",
    `> Generated by CodeJaguar · ${model} · ${findings.length} issue${findings.length !== 1 ? "s" : ""} found · ${generatedAt}`,
    "",
  ];

  if (summary) {
    lines.push("## Summary", "", summary, "");
  }

  if (sorted.length === 0) {
    lines.push("✅ No issues found. Code looks good!", "");
    return lines.join("\n");
  }

  lines.push("## Findings", "");
  for (const finding of sorted) {
    const location = finding.line ? `${finding.file}:${finding.line}` : finding.file;
    lines.push(
      `### [${finding.severity.toUpperCase()}] ${finding.category} — \`${location}\``,
      "",
      `**Description:** ${finding.description}`,
      "",
      `**Impact:** ${finding.impact}`,
      "",
      `**Recommendation:** ${finding.recommendation}`,
      ""
    );
  }

  return lines.join("\n");
}

/**
 * Render a security finding card.
 */
function renderSecurityFinding(finding: SecurityFinding): string {
  const color = severityColor(finding.severity);
  const location = finding.line
    ? `${finding.file}:${finding.line}`
    : finding.file;

  const lines = [
    color(`[${finding.severity}]`) +
      " " +
      chalk.bold(finding.category) +
      " — " +
      chalk.cyan(location),
    "",
    "  " + chalk.white(finding.description),
    "  " + chalk.gray("Impact: ") + finding.impact,
    "  " + chalk.gray("Fix: ") + chalk.green(finding.recommendation),
  ];

  if (finding.module) {
    lines.splice(2, 0, "  " + chalk.gray("Module: ") + finding.module);
  }

  return lines.join("\n");
}

/**
 * Render security scan results to the terminal.
 */
export function renderSecurityResults(
  findings: SecurityFinding[],
  stats: SecurityStats,
  providerUsed: string
): void {
  const header = renderHeader(
    "🛡️ Security Scan Results",
    `${stats.critical} critical, ${stats.high} high, ${stats.medium} medium, ${stats.low} low · ${providerUsed}`
  );

  console.log(header);

  if (findings.length === 0) {
    console.log(chalk.green("✅ No security issues found."));
    return;
  }

  // Sort by severity
  const severityOrder = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
  const sorted = [...findings].sort((a, b) => {
    const aVal = severityOrder[a.severity.toUpperCase() as keyof typeof severityOrder] ?? 4;
    const bVal = severityOrder[b.severity.toUpperCase() as keyof typeof severityOrder] ?? 4;
    return aVal - bVal;
  });

  for (const finding of sorted) {
    console.log(renderSecurityFinding(finding));
    console.log("");
  }
}

/**
 * Build a Markdown report for a security scan (for saving to disk).
 */
export function buildSecurityMarkdown(
  findings: SecurityFinding[],
  stats: SecurityStats,
  providerUsed: string,
  modelUsed: string,
  scanLabel: string,
  generatedAt: string
): string {
  const severityOrder = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
  const sorted = [...findings].sort((a, b) => {
    const aVal = severityOrder[a.severity.toUpperCase() as keyof typeof severityOrder] ?? 4;
    const bVal = severityOrder[b.severity.toUpperCase() as keyof typeof severityOrder] ?? 4;
    return aVal - bVal;
  });

  const model = modelUsed ? `${providerUsed}/${modelUsed}` : providerUsed;
  const lines: string[] = [
    `# Security Scan — ${scanLabel}`,
    "",
    `> Generated by CodeJaguar · ${model} · ${generatedAt}`,
    "",
    `**Summary:** ${stats.critical} critical · ${stats.high} high · ${stats.medium} medium · ${stats.low} low`,
    "",
  ];

  if (sorted.length === 0) {
    lines.push("✅ No security issues found.", "");
    return lines.join("\n");
  }

  lines.push("## Findings", "");
  for (const finding of sorted) {
    const location = finding.line ? `${finding.file}:${finding.line}` : finding.file;
    lines.push(`### [${finding.severity.toUpperCase()}] ${finding.category} — \`${location}\``, "");
    if (finding.module) {
      lines.push(`**Module:** ${finding.module}`, "");
    }
    lines.push(
      `**Description:** ${finding.description}`,
      "",
      `**Impact:** ${finding.impact}`,
      "",
      `**Recommendation:** ${finding.recommendation}`,
      ""
    );
  }

  return lines.join("\n");
}

/** A single architecture finding (mirrors the backend ArchitectureFinding). */
export interface ArchitectureFinding {
  severity: string;
  category: string;
  file?: string;
  description: string;
  recommendation: string;
}

/**
 * Build a Markdown report for an architecture review (for saving to disk).
 */
export function buildArchitectureMarkdown(
  findings: ArchitectureFinding[],
  improvements: string[],
  recommendations: string,
  providerUsed: string,
  modelUsed: string,
  generatedAt: string
): string {
  const severityOrder = { HIGH: 0, MEDIUM: 1, LOW: 2 };
  const sorted = [...findings].sort((a, b) => {
    const aVal = severityOrder[a.severity.toUpperCase() as keyof typeof severityOrder] ?? 3;
    const bVal = severityOrder[b.severity.toUpperCase() as keyof typeof severityOrder] ?? 3;
    return aVal - bVal;
  });

  const model = modelUsed ? `${providerUsed}/${modelUsed}` : providerUsed;
  const lines: string[] = [
    "# Architecture Review",
    "",
    `> Generated by CodeJaguar · ${model} · ${findings.length} finding${findings.length !== 1 ? "s" : ""} · ${generatedAt}`,
    "",
  ];

  if (sorted.length > 0) {
    lines.push("## Findings", "");
    for (const finding of sorted) {
      const where = finding.file ? ` — \`${finding.file}\`` : "";
      lines.push(
        `### [${finding.severity.toUpperCase()}] ${finding.category}${where}`,
        "",
        `**Description:** ${finding.description}`,
        "",
        `**Recommendation:** ${finding.recommendation}`,
        ""
      );
    }
  } else {
    lines.push("✅ No architectural issues found.", "");
  }

  if (improvements.length > 0) {
    lines.push("## Improvements", "");
    for (const imp of improvements) {
      lines.push(`- ${imp}`);
    }
    lines.push("");
  }

  if (recommendations) {
    lines.push("## Recommendations", "", recommendations, "");
  }

  return lines.join("\n");
}

/**
 * Build a Markdown document for a PR summary (for saving to disk).
 *
 * The backend already returns GitHub-ready Markdown; this just prepends a
 * provenance header comment.
 */
export function buildSummaryMarkdown(
  markdown: string,
  providerUsed: string,
  modelUsed: string,
  generatedAt: string
): string {
  const model = modelUsed ? `${providerUsed}/${modelUsed}` : providerUsed;
  return (
    `<!-- Generated by CodeJaguar · ${model} · ${generatedAt} -->\n\n` +
    markdown.trim() +
    "\n"
  );
}

/**
 * Build a Markdown report for a consensus review (for saving to disk).
 *
 * Shows only findings agreed on by multiple providers, annotated with which
 * models agreed on each.
 */
export function buildConsensusMarkdown(
  findings: ConsensusFinding[],
  providers: string[],
  minAgree: number,
  generatedAt: string
): string {
  const lines: string[] = [
    "# Code Review — Consensus",
    "",
    `> Generated by CodeJaguar · ${providers.join(", ")} · ` +
      `${findings.length} agreed finding${findings.length !== 1 ? "s" : ""} ` +
      `(≥${minAgree} of ${providers.length} models) · ${generatedAt}`,
    "",
  ];

  if (findings.length === 0) {
    lines.push(
      `✅ No findings were agreed on by at least ${minAgree} of the ${providers.length} providers.`,
      ""
    );
    return lines.join("\n");
  }

  lines.push("## Agreed Findings", "");
  for (const finding of findings) {
    const location = finding.line ? `${finding.file}:${finding.line}` : finding.file;
    lines.push(
      `### [${finding.severity.toUpperCase()}] ${finding.category} — \`${location}\``,
      "",
      `**Agreed by:** ${finding.agreedBy.join(", ")} (${finding.agreedBy.length}/${providers.length})`,
      "",
      `**Description:** ${finding.description}`,
      "",
      `**Impact:** ${finding.impact}`,
      "",
      `**Recommendation:** ${finding.recommendation}`,
      ""
    );
  }

  return lines.join("\n");
}
